// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoxhbjoxjqcizgjchoik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhveGhiam94anFjaXpnamNob2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjA4NDYsImV4cCI6MjA3MjUzNjg0Nn0.07Q8wF2PIPObcdlZiVfyGgosDd6e7o92cqbv5-UJMh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});